# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific aliases and functions
#alias getMake='cd $SYSLOCATION; svn checkout svn+ssh://$SVNUSER@belzebu.oa-cagliari.inaf.it/repos/ACS/tags/$SYSTEM_SVN_TAG/SystemMake'
#alias getTrunk='cd $SYSLOCATION; svn checkout svn+ssh://$SVNUSER@belzebu.oa-cagliari.inaf.it/repos/ACS/trunk/'
#alias getCDB='cd $ACS_CDB; ln -s $SYSLOCATION/trunk/Medicina/Configuration/CDB CDB'
alias ll='ls -la'
alias lt='ls -lt | more'
alias gittree='git log --oneline --graph --decorate --color --all'
function grepall() { find . -mount -type f -name "*$2" -print | xargs grep -i "$1" | more; }

##############################################
# DEFINING DEFAULT VALUES
# we don't want to override existing values 
# which can be defined by the testing 
# or building bot
##############################################
if [ -z "$INTROOT" ]; then
	export INTROOT=/system/introot
fi
if [ -z "$TARGETSYS" ]; then
	export TARGETSYS=SRT
fi
if [ -z "$ACS_CDB" ]; then
	export ACS_CDB=/system/configuration
fi

#. .acs/.bash_profile.acs
. $HOME/.acs/.bash_profile.acs

#specific for System runtime
#export ACS_LOG_STDOUT=11
#export ACS_LOG_CENTRAL=5
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
export MANAGER_REFERENCE=corbaloc::azdora:3000/Manager

#specific for system compilation
export DOCROOT=/system/docroot
export OPTIMIZE=0
export SYSLOCATION=/data/ACS/trunk
#Change the SVNUSER variable if installing for local development
export SVNUSER=azdora
export REPO_ROOT=/data/ACS
# this is for retrocompatibility
export SYSTEM_SVN_TAG=trunk
# this should include all the path to tag i.e. tags/noto-0.1 or trunk
export SYSTEM_REPO_TAG=trunk
export PATH=/usr/local/qt/bin/:$PATH
export QTDIR=/usr/local/qt

